__version__ = "0.1.0"

from .builders import (
    build_batch,
    build_basket_rule,
    build_calendar,
    build_distribution,
    build_failure_profile,
    build_machine,
    build_route_step,
    build_schedule_bundle,
    build_schedule_operation,
    build_time_window,
    build_travel_matrix,
)
from .engine import run_week
from .hooks import SimulationHooks
from .kairos_adapter import (
    KairosConversionResult,
    build_kairos_validation_hooks,
    build_schedule_bundle_from_kairos,
    validate_kairos_solution,
)
from .models import (
    BasketRule,
    Batch,
    BatchSummary,
    Calendar,
    DistributionSpec,
    EventRecord,
    FailureProfile,
    InitialBasketState,
    InitialMachineState,
    InitialOperationState,
    InitialSimulationState,
    InitialTransferState,
    Machine,
    MachineSummary,
    OperationResult,
    RouteStep,
    ScheduleBundle,
    ScheduleOperation,
    SimulationResult,
    TimeWindow,
    TravelMatrix,
)
from .tracker import build_product_tracker_lines, write_product_tracker
from .validator import (
    DeterministicValidationReport,
    OperationValidation,
    validate_deterministic_execution,
)
from .validation import ValidationError, validate_schedule_bundle
from .visualization import KairosGanttVisualizer, SimulationGanttVisualizer

__all__ = [
    "__version__",
    "BasketRule",
    "Batch",
    "BatchSummary",
    "Calendar",
    "DeterministicValidationReport",
    "DistributionSpec",
    "EventRecord",
    "FailureProfile",
    "InitialBasketState",
    "InitialMachineState",
    "InitialOperationState",
    "InitialSimulationState",
    "InitialTransferState",
    "KairosConversionResult",
    "KairosGanttVisualizer",
    "Machine",
    "MachineSummary",
    "OperationValidation",
    "OperationResult",
    "RouteStep",
    "ScheduleBundle",
    "ScheduleOperation",
    "SimulationHooks",
    "SimulationGanttVisualizer",
    "SimulationResult",
    "TimeWindow",
    "TravelMatrix",
    "ValidationError",
    "build_batch",
    "build_basket_rule",
    "build_calendar",
    "build_distribution",
    "build_failure_profile",
    "build_kairos_validation_hooks",
    "build_machine",
    "build_product_tracker_lines",
    "build_route_step",
    "build_schedule_bundle",
    "build_schedule_bundle_from_kairos",
    "build_schedule_operation",
    "build_time_window",
    "build_travel_matrix",
    "run_week",
    "validate_deterministic_execution",
    "validate_kairos_solution",
    "validate_schedule_bundle",
    "write_product_tracker",
]
